config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

# Static Routes
  get '/about', to: 'static_pages#about'
  get '/ashes', to: 'static_pages#ashes'
  get '/sponsors', to: 'static_pages#sponsors'
  get '/nyl-2019', to: 'static_pages#newyorklife'
  get '/membership', to: 'static_pages#membership'
# Login, Logout and Signup Routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, path: '/players' do
    member do
      put :paid, :admin, :remove_admin
    end
  end

  resources :schedules do
    collection do
      get :socials, :firsts, :seconds
    end
    member do
      get :available, :unavailable
    end
  end

  resources :account_activations, only: [:edit]
  resources :contact, only: [:index, :new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @upcoming = Schedule.where(date: next_week)
    @previous = Schedule.where(date: last_week).where.not(date: Date.today)
  end

  def about
  end

  def membership
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/partials/_logged_in.html.erb
<h1>This Weekends Games</h1>
<div class="row justify-content-around">
  <%= render 'static_pages/partials/upcoming' %>
</div>

<% if @previous.empty? %>
  <h3>There were no games last weekend.</h3>
<% else %>
  <h1 style="padding-top: 30px;">Last Weekends Games</h1>
  <div class="row justify-content-around">
    <%= render 'static_pages/partials/previous' %>
  </div>
<% end %>

app/views/static_pages/partials/_not_logged_in.html.erb
<div class="row">
  <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
    <h1>2019 Season Now Open!!!</h1>
    <p>
      Welcome to Marin Cricket Club, the best cricket experience in the Bay Area!
    </p>
    <p>
      Here you will find all the information
      <%= link_to "about our club and it's executive members", about_path %>
      and current season!
    </p>
    <p>
      We do have space available to players interested in joining one of our NCCA League Teams.
    </p>
    <p>
      If you would like to be part of our club,
      <%= link_to 'send us a message', contact_index_path %>
      and we will get back to you as soon as we can!
    </p>
    </br>
    <p>
      The sixth annual <%= link_to 'New York Life Tournent', nyl_2019_path %> was held on held July 13th!
      Congratulations to Team India defending their title!
    </p>
    <p>
      The annual <%= link_to 'Ashes game', ashes_path %> is schedule for August 17th. Please RSVP below:
    </p>
    <%= link_to 'RSVP Here!',
      'https://www.eventbrite.com/e/marin-cricket-club-ashes-2019-tickets-67068582937',
      class: 'btn btn-lg btn-success', target: 'blank' %>
    </br>
    </br>
    <p>Previous Socials members please create an account to sign up for this seasons games!</p>
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </br>
    </br>
    <p>Already a Socials member? Log in to sign up for upcoming games!</p>
    <%= link_to 'Log in now!', login_path, class: 'btn btn-lg btn-primary' %>
  </div>
  <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
    <%= link_to ashes_path do %>
      <%= image_tag('ashes.png', alt: 'New York Life 2019', class: 'img-fluid') %>
    <% end %>
  </div>
</div>

app/views/static_pages/partials/_previous.html.erb
<% @previous.where(team: 'Firsts').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Firsts</h3>
    <%= render schedule %>
  </div>
<% end %>

<% @previous.where(team: 'Seconds').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Seconds</h3>
    <%= render schedule %>
  </div>
<% end %>

<% @previous.where(team: 'Socials').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Socials</h3>
    <%= render schedule %>
  </div>
<% end %>

app/views/static_pages/partials/_upcoming.html.erb
<% @upcoming.where(team: 'Firsts').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Firsts</h3>
    <%= render schedule %>
  </div>
<% end %>

<% @upcoming.where(team: 'Seconds').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Seconds</h3>
    <%= render schedule %>
  </div>
<% end %>

<% @upcoming.where(team: 'Socials').each do |schedule| %>
  <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
    <h3 class="text-center">Socials</h3>
    <%= render schedule %>
  </div>
<% end %>