config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

# Static Routes
  get '/about', to: 'static_pages#about'
  get '/ashes', to: 'static_pages#ashes'
  get '/sponsors', to: 'static_pages#sponsors'
  get '/nyl-2019', to: 'static_pages#newyorklife'
  get '/membership', to: 'static_pages#membership'
# Login, Logout and Signup Routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, path: '/players' do
    member do
      put :paid, :admin, :remove_admin
    end
  end

  resources :schedules do
    collection do
      get :socials, :firsts, :seconds
    end
    member do
      get :available, :unavailable
    end
  end

  resources :account_activations, only: [:edit]
  resources :contact, only: [:index, :new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :player_stat, dependent: :destroy
  after_create :create_player_stat
  has_many :selections
  has_many :schedules, through: :selections
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email, :capitalize_name, :capitalize_surname
  before_create :create_activation_digest
  validates :name, :surname, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in database for persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def capitalize_name
      self.name = self.name.capitalize
    end

    def capitalize_surname
      self.surname = self.surname.capitalize
    end

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :paid]

  def index
    @users = User.where(activated: true)
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.avatar.attach(params[:avatar])
    if @user.save
      @user.send_activation_email
      flash[:info] = 'You must check your email and activate your account.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @user.avatar.attach(params[:avatar])
  end

  def update
    @user = User.find(params[:id])
    @user.avatar.attach(params[:avatar])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile Updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
    flash[:danger] = 'User has been deleted.'
  end

  def paid
    @user = User.find(params[:id])
    @user.update(paid: true)
    redirect_to users_url
    flash[:success] = @user.name + ' marked as having paid fees.'
  end

  def admin
    @user = User.find(params[:id])
    @user.update(admin: true)
    redirect_to users_url
    flash[:success] = @user.name + ' now has admin rights.'
  end

  def remove_admin
    @user = User.find(params[:id])
    @user.update(admin: false)
    redirect_to users_url
    flash[:danger] = @user.name + ' no longer has admin rights.'
  end

  private

    def user_params
      params.require(:user).permit(:name, :surname, :email, :password,
                            :password_confirmation, :role, :bats, :bowls)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_admin_buttons.html.erb
<%= link_to 'Delete', @user, class: 'btn btn-danger float-right',  method: :delete,
    data: { confirm: 'You sure brah? ' + @user.name + ' will be PERMANENTLY DELETED from the database.'} %>

<%= link_to 'Paid Fees', paid_user_path(@user),
    class: 'btn btn-success float-right', method: :put,
    data: { confirm: @user.name + ' has paid fees?' } unless @user.paid? %>

<%= link_to 'Make Admin', admin_user_path(@user),
    class: 'btn btn-warning float-right', method: :put,
    data: { confirm: 'Give ' + @user.name + ' Admin User rights?' } unless @user.admin? %>

<%= link_to 'Remove Admin', remove_admin_user_path(@user),
    class: 'btn btn-secondary float-right', method: :put,
    data: { confirm: 'Remove ' + @user.name + ' Admin User rights?' } if @user.admin? %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :first_name %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'First Name' %>

  <%= f.label :last_name %>
  <%= f.text_field :surname, class: 'form-control', placeholder: 'Last Name' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'Email Address' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>

  <%= f.label :role %>
  <%= f.select :role , ['Batsmen', 'Bowler', 'Wicketkeeper', 'All Rounder'], {}, class: 'form-control' %>

  <%= f.label :bats %>
  <%= f.select :bats , ['Left', 'Right'], {}, class: 'form-control' %>

  <%= f.label :bowls %>
  <%= f.select :bowls , ['Left', 'Right'], {}, class: 'form-control' %>

  <%= f.label :profile_photo %>
  <%= f.file_field :avatar %>

  <%= f.submit yield(:button_text), class:'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name + ' ' + user.surname, user %>

  <% if admin_logged_in? %>

      <%= link_to 'Delete', user, class: 'btn btn-danger float-right',  method: :delete,
          data: { confirm: 'You sure brah? ' + user.name + ' will be PERMANENTLY DELETED from the database.'} %>

      <%= link_to 'Paid Fees', paid_user_path(user),
          class: 'btn btn-success float-right', method: :put,
          data: { confirm: user.name + ' has paid fees?' } unless user.paid? %>

      <%= link_to 'Make Admin', admin_user_path(user),
          class: 'btn btn-warning float-right', method: :put,
          data: { confirm: 'Give ' + user.name + ' Admin User rights?' } unless user.admin? %>

      <%= link_to 'Remove Admin', remove_admin_user_path(user),
          class: 'btn btn-secondary float-right', method: :put,
          data: { confirm: 'Remove ' + user.name + ' Admin User rights?' } if user.admin? %>

  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:button_text, 'Save Changes') %>
<h1>Update Profile</h1>
<div class="form-group row justify-content-center">
  <div class="col-md-4">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Players') %>
<h1>All Players</h1>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, 'Create Account') %>
<h1>Sign Up</h1>

<div class="form-group row justify-content-center">
  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name + ' ' + @user.surname) %>
<div class="row">
  <aside class="col">
    <section class="user_info">
      <h1 class="float-left"><%= @user.name %> <%= @user.surname %></h1>
    </section>
      <p>Role: <%= @user.role %></p>
      <p>Bats: <%= @user.bats %></p>
      <p>Bowls: <%= @user.bowls %></p>
  </aside>
  <%= gravatar_for @user %>
</div>

<div class="table-responsive">
  <h6 class="text-muted">Batting Averages</h6>
	<%= render 'users/partials/batting_stats' %>
</div>
<div class="table-responsive">
  <h6 class="text-muted">Bowling and Feilding Averages</h6>
	<%= render 'users/partials/bowling_stats' %>
</div>

<% if admin_logged_in? %>
  <%= mail_to @user.email %>
<% end %>

<% unless @user.paid? %>
  <p>
    If you have already paid membership dues, please
    <%= mail_to('redhendery@gmail.com', 'email Red', target: 'blank', subject: 'Account Created on marincricketclub.com') %>
    and let him know you have created an account.
  </p>
  <p>
    If you have not paid your membership dues, please click the link below:
    <b>You are unable to sign up for Socials games until your dues have been paid.</b>
  </p>
  <%= link_to 'Memberships', membership_path, class: 'btn btn-lg btn-primary' %>
<% end %>

<% if admin_logged_in? %>
  <%= render 'admin_buttons' %>
<% end %>