config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

# Static Routes
  get '/about', to: 'static_pages#about'
  get '/ashes', to: 'static_pages#ashes'
  get '/sponsors', to: 'static_pages#sponsors'
  get '/nyl-2019', to: 'static_pages#newyorklife'
  get '/membership', to: 'static_pages#membership'
# Login, Logout and Signup Routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, path: '/players' do
    member do
      put :paid, :admin, :remove_admin
    end
  end

  resources :schedules do
    collection do
      get :socials, :firsts, :seconds
    end
    member do
      get :available, :unavailable
    end
  end

  resources :account_activations, only: [:edit]
  resources :contact, only: [:index, :new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  after_create :create_game_stat
  has_one :game_stat, dependent: :destroy
  has_many :selections
  has_many :users, through: :selections
  validates :opponent, :start_time, :series_game, :location, :team, presence: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :logged_in?, only: [:available, :unavailable]
  before_action :admin_user, only: [:new, :create, :edit, :destroy]

  def socials
    @schedules = Schedule.where(team: 'Socials').order(date: :asc)
  end

  def firsts
    @schedules = Schedule.where(team: 'Firsts').order(date: :asc)
  end

  def seconds
    @schedules = Schedule.where(team: 'Seconds').order(date: :asc)
  end

  def show
    @schedule = Schedule.find(params[:id])
    @no_of_games = Schedule.where(opponent: @schedule.opponent).count
    if logged_in?
      @available = @schedule.selections.find_by(user_id: current_user.id)
    end
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:success] = 'Game Added!'
      redirect_to @schedule
    else
      render 'new'
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update_attributes(schedule_params)
      flash[:success] = 'Game Updated!'
      redirect_to @schedule
    else
      render 'edit'
    end
  end

  def destroy
    Schedule.find(params[:id]).destroy
    flash[:success] = 'Game deleted'
    redirect_to root_url
  end

  def available
    @schedule = Schedule.find(params[:id])
    current_user.selections.create(schedule: @schedule)
    flash[:success] = 'Thank you ' + current_user.name + ' for signing up to play!'
    redirect_to @schedule
  end

  def unavailable
    @schedule = Schedule.find(params[:id])
    @selection = Selection.find_by(schedule_id: @schedule.id, user_id: current_user.id)
    @selection.destroy
    flash[:danger] = current_user.name + ' you will not be selected to play.'
    redirect_to @schedule
  end

  private

    def schedule_params
      params.require(:schedule).permit(:date, :opponent, :start_time, :series_game,
                                  :team, :location, :home_score, :home_wickets, :home_overs,
                                  :away_score, :away_wickets, :away_overs, user_ids: [])
    end

    def admin_user
      if admin_logged_in?
      else redirect_to root_url
      end
    end

end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def next_week
    Date.current..(Date.current + 6)
  end

  def last_week
    (Date.current - 6)..Date.current
  end

end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :date %>
  <%= f.date_field :date, class: 'form-control' %>

  <%= f.label :team %>
  <%= f.select :team, ['Firsts', 'Seconds', 'Socials'], {}, class: 'form-control' %>

  <%= f.label :opponent %>
  <%= f.text_field :opponent, class: 'form-control' %>

  <%= f.label :start_time %>
  <%= f.time_select :start_time, {}, class: 'form-control' %>

  <%= f.label :Series_Game %>
  <%= f.text_field :series_game, class: 'form-control' %>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>

  <%= f.submit yield(:button_text), class:'btn btn-primary' %>

<% end %>

app/views/schedules/_schedule.html.erb
<div class="card-deck">
  <div class="card text-center">
    <div class="card-header">
      <h5 class="card-title">
        <strong>
          <% if schedule.opponent == 'Intraclub' %>
            <%= schedule.opponent %> - Bears vs. Eagles
          <% else %>
            Marin <%= schedule.team %> vs. <%= schedule.opponent %>
          <% end %>
        </strong>
      </h5>
    </div>

    <div class="card-body">
      <% unless schedule.home_score.nil? %>

        <% if schedule.opponent == 'Intraclub' %>

          <div class="row">
            <div class="col-6">
              <h4><bold>Marin Bears</bold></h4>
              <h5 class="card-text"><%= schedule.home_score %>/<%= schedule.home_wickets %></h5>
              <h5 class="card-text"><%= schedule.home_overs %></h5>
            </div>
            <div class="col-6">
              <h4><bold>Marin Eagles</bold></h4>
              <h5 class="card-text"><%= schedule.away_score %>/<%= schedule.away_wickets %></h5>
              <h5 class="card-text"><%= schedule.away_overs %></h5>
            </div>
            <div class="col-12">
              <br>
              <br>
              <% if schedule.home_score > schedule.away_score %>
                <h1>Bears win!</h1>
              <% else %>
                <h1>Eagles win!</h1>
              <% end %>
            </div>
          </div>

        <% else %>

          <div class="row">
            <div class="col-6">
              <h4><bold>Marin <%= schedule.team %></bold></h4>
              <h5 class="card-text"><%= schedule.home_score %>/<%= schedule.home_wickets %></h5>
              <h5 class="card-text"><%= schedule.home_overs %></h5>
            </div>
            <div class="col-6">
              <h4><bold><%= schedule.opponent %></bold></h4>
              <h5 class="card-text"><%= schedule.away_score %>/<%= schedule.away_wickets %></h5>
              <h5 class="card-text"><%= schedule.away_overs %></h5>
            </div>
            <div class="col-12">
              <br>
              <br>
              <% if schedule.home_score > schedule.away_score %>
                <h1><%= schedule.team %> win!</h1>
              <% else %>
                <h1><%= schedule.opponent %> win</h1>
              <% end %>
            </div>
          </div>

        <% end %>

      <% else %>

        <p class="card-text">When: <%= schedule.date.strftime('%A %B %d') %></p>
        <p class="card-text">Game <%= schedule.series_game %></p>
        <p class="card-text">Where: <%= schedule.location %></p>

      <% end %>

      <% if schedule.team == 'Socials' %>

        <% if logged_in? == false && next_week.cover?(schedule.date) %>
          <%= link_to 'Sign Up for Selection', login_path, class: 'btn btn-success' %>
        <% elsif logged_in? && current_user.paid == false %>
          <%= link_to 'Sign Up for Selection', membership_path, class: 'btn btn-success' %>
        <% end %>

        <% unless schedule.date < Date.today + 54.5.hours %>
          <% if logged_in? && paid && next_week.cover?(schedule.date) %>
            <% if schedule.selections.find_by(user_id: current_user.id) %>
              <%= link_to 'Withdraw from Selection', unavailable_schedule_path(schedule),
                 class: 'btn btn-danger', data: { confirm: 'Are you sure? You will not be selected to play.'} %>
            <% else %>
              <%= link_to 'Sign Up for Selection', available_schedule_path(schedule), class: 'btn btn-success' %>
            <% end %>
          <% end %>
        <% end %>

      <% end %>

    </div>
    <div class="card-footer">
      <span><%= link_to 'Game Information', schedule %></span>
      <% if admin_logged_in? %>
        <span class="float-left"><%= link_to 'Edit Game', edit_schedule_path(schedule) %></span>
        <span class="float-right"><%= link_to 'Delete Game', schedule, method: :delete, data: { confirm: 'You sure brah?' } %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/_score.html.erb
<%= form_for(@schedule) do |f| %>

  <%= f.label :marin_score %>
  <%= f.number_field :home_score, class: 'form-control' %>

  <%= f.label :marin_wickets %>
  <%= f.number_field :home_wickets, class: 'form-control' %>

  <%= f.label :marin_overs %>
  <%= f.text_field :home_overs, class: 'form-control' %>

  <%= f.label :opponent_score %>
  <%= f.number_field :away_score, class: 'form-control' %>

  <%= f.label :opponent_wickets %>
  <%= f.number_field :away_wickets, class: 'form-control' %>

  <%= f.label :opponent_overs %>
  <%= f.text_field :away_overs, class: 'form-control' %>

  <%= f.submit yield(:button_text), class:'btn btn-primary' %>

<% end %>

app/views/schedules/_selection.html.erb
<%= form_for(@schedule) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <p>Total Player Signups: <%= @schedule.selections.count %></p>

  <%= hidden_field_tag 'schedule[user_ids][]', nil %>
  <% @schedule.users.each do |user| %>
    <%= check_box_tag 'schedule[user_ids][]', user.id, @schedule.user_ids.include?(user.id), id: dom_id(user) %>
    <p><strong><%= label_tag dom_id(user), user.name %> <%= user.surname %></strong></p>
    <p>Games played: <%= user.player_stat.games_played + user.selections.count - 1 %></p>
    <!-- <p>Last played:
      <%# <% if user.selections[-2].blank? %> %>
        None
      <%# <% else %> %>
        <%# <%= user.selections[-2].schedule.date.strftime('%A %B %d') %> %>
      <%# <% end %> %>
    </p> -->
  <% end %>

  <%= submit_tag 'Save Lineup', class: 'btn btn-success', data: { confirm: 'Confirm Lineup?' } %>

<% end %>

app/views/schedules/edit.html.erb
<% provide(:title, 'Edit Game') %>
<% provide(:button_text, 'Save Changes') %>

<% if @schedule.selections.empty? %>

  <h1>Update Game</h1>
  <div class="form-group row justify-content-around">
    <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-12">
      <h3>Update Game Details</h3>
      <%= render 'form' %>
    </div>

    <% if @schedule.date < Date.today %>
    <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-12">
        <h3>Game Score</h3>
        <%= render 'score' %>
      </div>
    <% end %>
  </div>

<% else %>

  <h1>Update Game</h1>
  <div class="form-group row justify-content-around">
    <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-12">
      <h3>Update Game Details</h3>
      <%= render 'form' %>
    </div>

    <% if next_week.cover?(@schedule.date) %>
      <div class="col-md-4">
        <h3>Player Selection</h3>
        <%= render 'selection' %>
      </div>
    <% else %>

      <% if @schedule.date < Date.today %>
      <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-12">
          <h3>Game Score</h3>
          <%= render 'score' %>
        </div>
      <% end %>

    <% end %>
  </div>

<% end %>

app/views/schedules/firsts.html.erb
<% provide(:title, 'First XI Games') %>
<h1>2019 First XI Schedule</h1>
<div class="row">
  <% @schedules.each do |schedule| %>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
      <%= render schedule %>
    </div>
  <% end %>
</div>

<%= link_to 'Add Game', new_schedule_path, class: 'btn btn-lg btn-primary' if admin_logged_in? %>

app/views/schedules/index.html.erb
<% provide(:title, 'All Games') %>
<h1>2019 Marin Socials Schedule</h1>
<div class="row">
  <% @schedules.each do |schedule| %>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
      <%= render schedule %>
    </div>
  <% end %>
</div>

<%= link_to 'Add Game', new_schedule_path, class: 'btn btn-lg btn-primary' if admin_logged_in? %>

app/views/schedules/new.html.erb
<% provide(:title, 'Add Schedule') %>
<% provide(:button_text, 'Create Game') %>
<h1>Create Game</h1>
<div class="form-group row justify-content-center">
  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

app/views/schedules/seconds.html.erb
<% provide(:title, 'Second XI Games') %>
<h1>2019 Second XI Schedule</h1>
<div class="row">
  <% @schedules.each do |schedule| %>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
      <%= render schedule %>
    </div>
  <% end %>
</div>

<%= link_to 'Add Game', new_schedule_path, class: 'btn btn-lg btn-primary' if admin_logged_in? %>

app/views/schedules/show.html.erb
<% provide(:title, @schedule.opponent) %>

  <div class="row justify-content-around">
    <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 col-12">
      <%= render 'schedules/partials/match_centre' %>
      <%= render 'schedules/partials/scorecard' if Date.today >= @schedule.date - 2 %>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12">
      <%= render 'schedules/partials/run_times' %>
    </div>
  </div>
  <%= render 'schedules/partials/logged_in' %>

  <% if @schedule.team == 'Socials' %>
    <div class="row justify-content-around">
      <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4 col-4">
        <%= render 'schedules/partials/paypal_button' if Date.today >= @schedule.date - 3 %>
      </div>
    </div>
  <% end %>

<%= render 'schedules/partials/admin_buttons' %>

app/views/schedules/socials.html.erb
<% provide(:title, 'Socials XI Games') %>
<h1>2019 Marin Socials Schedule</h1>
<div class="row">
  <% @schedules.each do |schedule| %>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
      <%= render schedule %>
    </div>
  <% end %>
</div>

<%= link_to 'Add Game', new_schedule_path, class: 'btn btn-lg btn-primary' if admin_logged_in? %>