config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

# Static Routes
  get '/about', to: 'static_pages#about'
  get '/ashes', to: 'static_pages#ashes'
  get '/sponsors', to: 'static_pages#sponsors'
  get '/nyl-2019', to: 'static_pages#newyorklife'
  get '/membership', to: 'static_pages#membership'
# Login, Logout and Signup Routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, path: '/players' do
    member do
      put :paid, :admin, :remove_admin
    end
  end

  resources :schedules do
    collection do
      get :socials, :firsts, :seconds
    end
    member do
      get :available, :unavailable
    end
  end

  resources :account_activations, only: [:edit]
  resources :contact, only: [:index, :new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/partials/_if_logged_in.html.erb
<li class="dropdown">
	<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">My Profile</a>
	<ul class="dropdown-menu">
	  <li>
	  	<%= link_to 'Profile', current_user, class: 'dropdown-item' %>
	  </li>
	  <li>
	  	<%= link_to 'Settings', edit_user_path(current_user), class: 'dropdown-item' %>
	  </li>
	  <div class="dropdown-divider"></div>
	  <li>
	    <%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %>
	  </li>
	</ul>
</li>

app/views/layouts/partials/_nav_links.html.erb
<li class="nav-item">
  <%= link_to 'Players', users_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'About', about_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'Contact', contact_index_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'Sponsors', sponsors_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'Memberships', membership_path, class: 'nav-link' unless logged_in? && current_user.paid? %>
</li>
<li class="dropdown">
	<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Schedules</a>
	<ul class="dropdown-menu">
    <li class="nav-item">
      <%= link_to 'Socials', socials_schedules_path, class: 'dropdown-item' %>
    </li>
    <li class="nav-item">
      <%= link_to 'First XI', firsts_schedules_path, class: 'dropdown-item' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Second XI', seconds_schedules_path, class: 'dropdown-item' %>
    </li>
  </ul>
</li>